name: brave-assets
version: 0.1.0.0
github: "githubuser/brave-assets"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
    - README.md
    - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/brave-assets#readme>

dependencies:
    - aeson <= 1.4.7.1
    - aeson-casing <= 0.2.0.0
    - base >= 4.7 && < 5
    - bytestring <= 0.10.10.1
    - containers <= 0.6.4.1
    - directory <= 1.3.6.0
    - process <= 1.6.9.0
    - optparse-applicative <= 0.15.1.0
    - process <= 1.6.9.0
    - regex-base <= 0.94.0.0
    - regex-posix <= 0.96.0.0
    - req <= 3.9.0
    - scalpel <= 0.6.2
    - string-interpolate <= 0.2.1.0
    - text <= 1.2.4.0
    - text-conversions <= 0.3.1

library:
    source-dirs: src

executables:
    brave-assets-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - brave-assets

tests:
    brave-assets-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - brave-assets
